language: ruby
env:
  - "RAILS_VERSION=4.2.7.1"

rvm:
  - 2.3.2
before_script:
  - cd test/dummy
  - RAILS_ENV=test rake db:create db:migrate
  - RAILS_ENV=remote rake db:create db:migrate
script:
  - cd ${TRAVIS_BUILD_DIR}
  - rake test
